version: '3.4'

services:
  scoter-api:
    image: escootertcpcommunication
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3005:3005
